services:
  # Backend Service
  - type: web
    name: asphalt-backend
    env: python
    buildCommand: "pip install -r backend/app/requirements.txt"
    startCommand: "cd backend/app && gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: OSRM_HOST
        value: http://100.30.34.94:5000

  # Frontend Service
  - type: web
    name: asphalt-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm start"
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: asphalt-backend
          property: url
      - key: NEXT_PUBLIC_OSRM_URL
        value: http://100.30.34.94:5000
